name: Deploy docs with theme-hope

on:
  push:
    branches:
      - theme-hope

jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Build docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: netlify
          folder: docs/.vuepress/dist
